### ISSUE TITLE
No properties dialog with 3.7

### ISSUE THREAD

**Issue by mnlipp** [eclipse-pmd/eclipse-pmd#176]
Right click on a project, open Properties dialog. Click on PMD. Results in a "Problem Occured" dialog with details: `An error has occurred. See error log for more details. Either ID or absoluteRuleSetReferenceId is required`.

Logfile:
```
!ENTRY org.eclipse.jface 4 2 2024-05-01 12:38:34.632
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.jface".
!STACK 0
java.lang.IllegalArgumentException: Either ID or absoluteRuleSetReferenceId is required
	at net.sourceforge.pmd.lang.rule.internal.RuleSetReferenceId.<init>(RuleSetReferenceId.java:153)
	at net.sourceforge.pmd.lang.rule.RuleSetLoader.loadFromResource(RuleSetLoader.java:139)
	at ch.acanda.eclipse.pmd.cache.RuleSetsCacheLoader.loadRuleSet(RuleSetsCacheLoader.java:46)
	at ch.acanda.eclipse.pmd.properties.PMDPropertyPageModelTransformer.getRuleSetErrorMessage(PMDPropertyPageModelTransformer.java:65)
	at ch.acanda.eclipse.pmd.properties.PMDPropertyPageModelTransformer.toViewModel(PMDPropertyPageModelTransformer.java:59)
	at ch.acanda.eclipse.pmd.properties.PMDPropertyPageModelTransformer.lambda$2(PMDPropertyPageModelTransformer.java:50)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.TreeMap$KeySpliterator.forEachRemaining(TreeMap.java:3064)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at ch.acanda.eclipse.pmd.properties.PMDPropertyPageModelTransformer.toViewModels(PMDPropertyPageModelTransformer.java:50)
	at ch.acanda.eclipse.pmd.properties.PMDPropertyPageController.init(PMDPropertyPageController.java:58)
	at ch.acanda.eclipse.pmd.properties.PMDPropertyPage.setElement(PMDPropertyPage.java:35)
	at org.eclipse.ui.internal.dialogs.RegistryPageContributor.createPage(RegistryPageContributor.java:145)
	at org.eclipse.ui.internal.dialogs.PropertyPageNode.createPage(PropertyPageNode.java:57)
	at org.eclipse.jface.preference.PreferenceDialog.createPage(PreferenceDialog.java:1280)
	at org.eclipse.ui.internal.dialogs.FilteredPreferenceDialog.createPage(FilteredPreferenceDialog.java:326)
	at org.eclipse.jface.preference.PreferenceDialog.showPage(PreferenceDialog.java:1166)
	at org.eclipse.ui.internal.dialogs.FilteredPreferenceDialog.showPage(FilteredPreferenceDialog.java:618)
	at org.eclipse.jface.preference.PreferenceDialog$5.lambda$0(PreferenceDialog.java:660)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:67)
	at org.eclipse.jface.preference.PreferenceDialog$5.selectionChanged(PreferenceDialog.java:657)
	at org.eclipse.jface.viewers.StructuredViewer$3.run(StructuredViewer.java:820)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:174)
	at org.eclipse.jface.viewers.StructuredViewer.firePostSelectionChanged(StructuredViewer.java:817)
	at org.eclipse.jface.viewers.ColumnViewer.firePostSelectionChanged(ColumnViewer.java:1065)
	at org.eclipse.jface.viewers.StructuredViewer.handlePostSelect(StructuredViewer.java:1185)
	at org.eclipse.swt.events.SelectionListener$1.widgetSelected(SelectionListener.java:84)
	at org.eclipse.jface.util.OpenStrategy.firePostSelectionEvent(OpenStrategy.java:283)
	at org.eclipse.jface.util.OpenStrategy$1.lambda$1(OpenStrategy.java:437)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:5040)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4520)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at org.eclipse.ui.dialogs.PropertyDialogAction.run(PropertyDialogAction.java:154)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:474)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:581)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:415)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5855)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1529)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5065)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4517)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1151)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1042)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:152)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:639)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:546)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:173)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:143)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:109)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:439)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:271)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:651)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:588)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1459)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1432)
```

Downgrading to 3.6 again works around the problem.

The project's `.eclipse-pmd`:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<eclipse-pmd xmlns="http://acanda.ch/eclipse-pmd/0.8" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://acanda.ch/eclipse-pmd/0.8 http://acanda.ch/eclipse-pmd/eclipse-pmd-0.8.xsd">
  <analysis enabled="true" />
  <rulesets>
    <ruleset name="Custom Rules" ref="JGrapes-WebConsole/ruleset.xml" refcontext="workspace" />
  </rulesets>
</eclipse-pmd>
```

The problem also occurs with an empty `ruleset.xml`, but just in case, here's my `ruleset.xml`:
```xml
<?xml version="1.0"?>

<ruleset name="Custom Rules"
        xmlns="http://pmd.sourceforge.net/ruleset/2.0.0"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://pmd.sourceforge.net/ruleset/2.0.0 https://pmd.sourceforge.io/ruleset_2_0_0.xsd">
    <description>
JGrapes rules
    </description>

    <exclude-pattern>.*/test/.*</exclude-pattern>
    <exclude-pattern>.*/node_modules/.*</exclude-pattern>

    <rule ref="category/java/bestpractices.xml">
        <exclude name="AccessorMethodGeneration"/>
        <exclude name="AvoidReassigningParameters"/>
    </rule>
    
    <rule ref="category/java/codestyle.xml">
        <exclude name="OnlyOneReturn"/>
        <exclude name="LocalVariableCouldBeFinal"/>
        <exclude name="MethodArgumentCouldBeFinal"/>
        <exclude name="AtLeastOneConstructor"/>
        <exclude name="DefaultPackage"/>
        <exclude name="CallSuperInConstructor"/>
        <exclude name="AbstractNaming"/>
    </rule>
    <rule ref="category/java/codestyle.xml/LongVariable">
      <properties>
         <property name="minimum" value="25" />
      </properties>
    </rule>
    <rule ref="category/java/codestyle.xml/FieldNamingConventions">
        <properties>
            <property name="exclusions" value="serialVersionUID,serialPersistentFields,logger" />
        </properties>
    </rule>
    <rule ref="category/java/codestyle.xml/ShortVariable">
        <properties>
            <property name="violationSuppressRegex" 
                value="Avoid variables with short names like id"/>
        </properties>
    </rule>
    
    <rule ref="category/java/design.xml">
        <exclude name="LawOfDemeter"/>
    </rule>
    <rule ref="category/java/design.xml/NcssCount">
      <properties>
         <property name="methodReportLevel" value="35" />
      </properties>
    </rule>    
    <rule ref="category/java/design.xml/CyclomaticComplexity">
      <properties>
         <property name="methodReportLevel" value="15" />
      </properties>
    </rule>    
    <rule ref="category/java/design.xml/NPathComplexity">
      <properties>
         <property name="reportLevel" value="300" />
      </properties>
    </rule>    
    <rule ref="category/java/design.xml/TooManyMethods">
      <properties>
         <property name="maxmethods" value="20" />
      </properties>
    </rule>    
    <rule ref="category/java/design.xml/ExcessiveImports">
      <properties>
         <property name="minimum" value="50" />
      </properties>
    </rule>    
    
    <rule ref="category/java/documentation.xml">
        <exclude name="CommentSize"/>
    </rule>
    <rule ref="category/java/documentation.xml/CommentRequired">
      <properties>
         <property name="fieldCommentRequirement" value="Ignored" />
      </properties>
    </rule>    
    
    <rule ref="category/java/errorprone.xml">
        <exclude name="AvoidFieldNameMatchingMethodName"/>
        <exclude name="BeanMembersShouldSerialize"/>
        <exclude name="NullAssignment"/>
        <exclude name="UseProperClassLoader"/>
    </rule>
    
    <rule ref="category/java/multithreading.xml">
        <exclude name="DoNotUseThreads"/>
    </rule>
    
    <rule ref="category/java/performance.xml">
        <exclude name="SimplifyStartsWith"/>
    </rule>
    
</ruleset>
```

**Comment by acanda** [comment]
Could it be that you have renamed the Eclipse project or the folder where your ruleset.xml is stored? The path to your ruleset in your `.eclipse-pmd` is `JGrapes-WebConsole/ruleset.xml`, so you should either have a project called `JGrapes-WebConsole` in your workspace or a folder with that name in your workspace folder. Changing `JGrapes-WebConsole` to the new name in `.eclipse-pmd` and restarting Eclipse would fix the problem in this case.

I will also add a catch for the IllegalArgumentException in the next release so that you can still open the PMD properties.

**Comment by acanda** [comment]
I have released a new version with a fix that should help with opening the PMD property page. My guess is that the plugin still cannot find the ruleset.xml but you should now get a better error message on the property page.

**Comment by mnlipp** [comment]
I can open the dialog again and pmd is executed (checked by introducing problem, saving, and removing it again).

The dialog looks a bit strange, thought.

![image](https://github.com/eclipse-pmd/eclipse-pmd/assets/1446020/7bb78ee0-eab5-4ef1-906e-2a229c6d8931)

Seems like the plugin likes/dislikes my configuration at the same time. The warning (mouse over) is "file does not exist" which makes absolutely no sense as I have only one entry in my `.eclipse-pmd` (hasn't changed from what is shown above).

The log file only has (positive) entries such as `!MESSAGE Invalidating cache for org.jgrapes.webconlet.oidclogin` and `!MESSAGE RuleSetsCache: loading rule sets for project org.jgrapes.webconlet.oidclogin`.

**Comment by acanda** [comment]
Do you have another project in the same workspace, with its own `.eclipse-pmd`, but with a slightly different ruleset configuration? E.g. with a lower case `c` in the `ref` like this: `<ruleset name="Custom Rules" ref="JGrapes-Webconsole/ruleset.xml" refcontext="workspace" />`. This would explain the first entry with the warning icon. The value in the `ref` attribute is case sensitive and must match the project name exactly.

If this is the case, then changing the lower case `c` to upper case in the corresponding `.eclipse-pmd` should solve the problem. Make sure you check all projects in your workspace. The invalid entry will not disappear until it is fixed in all configurations.

**Comment by mnlipp** [comment]
Yes, there was a typo in one of the files. Thanks!
