### ISSUE TITLE
Install error in Eclipse 2023-03 via Eclipse Marketplace

### ISSUE THREAD

**Issue by flemingadam** [eclipse-pmd/eclipse-pmd#70]
I am unable to install eclipse-pmd on Eclipse 2023-03 via the Eclipse Marketplace.

Eclipse Error Message:
```
HTTP Server 'Internal Error': https://acanda.jfrog.io/artifactory/eclipse-pmd/latest/content.xml

org.eclipse.ecf.filetransfer.BrowseFileTransferException: HttpComponents connection error response code 500.
	at org.eclipse.ecf.provider.filetransfer.httpclient5.HttpClientFileSystemBrowser.runRequest(HttpClientFileSystemBrowser.java:281)
	at org.eclipse.ecf.provider.filetransfer.browse.AbstractFileSystemBrowser$DirectoryJob.run(AbstractFileSystemBrowser.java:71)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

There is not a `content.xml` file in the `latest` directory but there is a `content.xml.xz` file and I am not familiar with JFrog's internals, so I don't know if that is correct or not.  When I browse to https://acanda.jfrog.io/artifactory/eclipse-pmd/latest/content.xml, I receive the response

```json
{
  "errors": [
    {
      "status": 404,
      "message": "children items not found on all virtual repos"
    }
  ]
}
```

Eclipse Information:
```
eclipse.buildId=4.27.0.20230309-1200
java.version=17.0.6
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.java.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.java.product
```

**Comment by eclipse-pmd** [comment]
I recently moved the repository to JFrog, but it unfortunately turned out to not be very reliable. I now moved it to GitHub which hopefully resolves those issues. This results in a new update site URL: https://eclipse-pmd.acanda.ch/release/latest.

You can either manually update this URL in the "Available Software Sites" preferences or uninstall and then reinstall the plugin from the marketplace again.
